import React from 'react';
import cowboyPetah from '../assets/Cowboy-Petah.jpg';
import longStick from '../assets/Long-Stick.jpg';
import gordieHowe from '../assets/Gordie-Howe.jpg';
import farewellCake from '../assets/Farewell-Cake.jpg';

const WT4Report = () => {
  return (
    <div className="container mx-auto py-16 px-4 mt-10 bg-base-200 text-justify">
      <h1 className="text-3xl font-bold mb-6 text-center">Co-op Work Term 4 Report</h1>
      <section className="space-y-8">
        {/* Introduction Section */}
        <div className="bg-base-300 p-8 rounded-xl flex flex-col md:flex-row gap-8">
          <div className="md:w-1/2 flex flex-col justify-center">
            <h2 className="font-bold text-2xl mb-4">Introduction</h2>
            <p className="text-lg leading-relaxed mb-4">
              Welcome to my fourth co-op work term report! Over the Summer 2026 semester, I had the opportunity to return to P&P Optica as a Data Services Technician Co-op.
              <br /><br />
              Returning to P&P Optica for another term allowed me to further strengthen the technical, professional, and interpersonal skills I developed during my previous work term here. I was able to take on more responsibility, work on new coding projects, and become more confident working in a production-level programming environment. My supervisor mentioned that this was the busiest year the company had ever had, and this was absolutely true as being on the Data Services team means working with nearly every customer we have!
            </p>
            <h2 className="font-bold text-2xl mb-4 mt-4">Employer Information</h2>
            <p className="text-lg leading-relaxed">
              During this work term, I continued working under Jenny Udema, the Data Services Manager.
              <br /><br />
              During my second term at P&P Optica, I was able to better develop my understanding of the software and systems that support our Smart Imaging System. I also had the opportunity to work more independently while collaborating with different members of the team.
              <br /><br />
              Being part of the Data Services team gave me the chance to work on a wide variety of projects including software development, data processing, system testing, and customer data collections. On one data collection, I even got an authentic cowboy hat!
            </p>
          </div>
          <div className="md:w-1/2 flex justify-center items-center">
            <div className='w-full max-w-[550px] aspect-square rounded-[20%] overflow-hidden mx-auto shadow-lg flex-shrink-0'>
              <img
                src={cowboyPetah}
                alt="Me in a Cowboy Hat"
                className="w-full h-full object-cover object-[center_50%]"
              />
            </div>
          </div>
        </div>
        {/* Achievements Section */}
        <div className="bg-base-300 p-8 rounded-xl space-y-16">
          <h2 className="font-bold text-3xl mb-4 border-b border-base-100 pb-2 text-center">Achievements</h2>
          <div className="flex flex-col gap-2 items-left">
              <h3 className="font-bold text-xl text-primary">Python Data Post-Processing Tool</h3>
              <p className="text-lg leading-relaxed">
                One of my biggest accomplishments during this work term was developing a new data post-processing tool in Python. This gave me the opportunity to work in a production-level programming environment and build upon existing code used by the company.
                <br /><br />
                The tool involved working with data generated by our systems and processing it into a more useful format for analysis, and it introduced me to Python libraries I had only used briefly, including Matplotlib and NumPy. Through this project, I became much more comfortable working with Python professionally and learned how to work with existing code rather than starting the project entirely from scratch.
                <br /><br />
                This was one of the most valuable programming experiences I have had during my co-op terms, as it allowed me to apply the programming skills I have developed through school to a real-world software project. My supervisor noted that I was able to grasp the team's software fairly quickly and even offer recommendations of my own. Sometimes I was able to teach her a few new things along the way.
              </p>
          </div>
          <div className="flex flex-col md:flex-row-reverse gap-8 items-center">
            <div className="md:w-1/2">
              <h3 className="font-bold text-xl mb-2 text-primary">System Testing & Foreign Material Generation</h3>
              <p className="text-lg leading-relaxed">
                Another major part of my work this term was preparing various materials for system testing. One example involved picking up a long 2x4 piece of wood from Home Depot and cutting it down into smaller pieces with specific measurements using a band saw and an Exacto knife set.
                <br /><br />
                These foreign materials were used to test and refine the Smart Imaging System. The work required a high level of precision, especially since pieces had to be cut within +/- 0.25 mm of the target size. My supervisor rated my quality of work as Outstanding this term, noting that my measurements were consistently within range, which meant she no longer needed to sanity check every piece I generated. I was able to maintain that same level of precision even during projects with tight deadlines.
                <br /><br />
                This was a great example of how my role involved more than just programming. I was able to work directly with the physical system and better understand how software, hardware, and data all work together!
              </p>
            </div>
            <div className="md:w-1/2 flex justify-center w-full">
              <img
                src={longStick}
                alt="Wooden test material used for system testing"
                className='w-full max-w-[550px] rounded-[20%] aspect-square shadow-lg object-cover'
              />
            </div>
          </div>
          <div className="flex flex-col md:flex-row gap-8 items-center">
            <div className="md:w-1/2">
              <h3 className="font-bold text-xl mb-2 text-primary">Customer Data Collection in the United States</h3>
              <p className="text-lg leading-relaxed">
                I also had some incredible opportunities to participate in customer data collections in the United States. Traveling to customer sites gave me valuable experience working directly with the Smart Imaging System outside of the office and seeing how the system is used in a real-world environment.
                <br /><br />
                These trips also helped me become more comfortable communicating with customers and working alongside my coworkers in unfamiliar environments. The data collected during these trips is important for improving our systems and supporting the development of our machine learning models.
                <br /><br />
                During the term, I was able to travel to four different factories, far exceeding my original goal at least one. These experiences were some of the biggest highlights of my work terms here at PPO, and gave me a much better understanding of the customer-facing side of the work we do.
              </p>
            </div>
            <div className="md:w-1/2 flex justify-center w-full">
              <img
                src={gordieHowe}
                alt="Crossing the new Gordie Howe International Bridge during a customer data collection trip"
                className='w-full max-w-[550px] rounded-[20%] aspect-square shadow-lg object-cover'
              />
            </div>
          </div>
        </div>
        {/* Learning Goals Section */}
        <div className="bg-base-300 p-8 rounded-xl">
          <h2 className="font-bold text-3xl mb-6 text-center border-b border-base-100 pb-2">Learning Goals</h2>
          <div className="space-y-6">
            <div className="bg-base-200 p-6 rounded-xl shadow-inner">
              <h3 className="font-bold text-xl mb-3 text-secondary">Goal 1: Technological Literacy</h3>
              <p className="text-lg leading-relaxed">
                <strong>Goal:</strong> My first goal for this term is to expand my ability to program in a production level environment, specifically in Python.<br /><br />
                <strong>Action Plan:</strong> To achieve this goal, I will seek out opportunities to develop tools that automate specific processes or improve existing tools used by our team.<br /><br />
                <strong>Measure of Success:</strong> To measure the success of this goal, I plan to learn and utilize at least one new Python library through the projects I work on during the term.<br /><br />
                <strong>Reflection:</strong> During my second four month term here at P&P Optica, I got the wonderful opportunity to develop a new data post-processing tool in Python. This script utilized many existing pieces of code from the company code base, as well as Python libraries such as Matplotlib, NumPy, and more. This script gave me the chance to use so many vast libraries that were completely new to me; I am happy to say I successfully achieved this goal! I learned an incredible amount during the programming of this tool and it was an invaluable experience to me during my time here.
              </p>
            </div>
            <div className="bg-base-200 p-6 rounded-xl shadow-inner">
              <h3 className="font-bold text-xl mb-3 text-secondary">Goal 2: Communicating</h3>
              <p className="text-lg leading-relaxed">
                <strong>Goal:</strong> My second goal for this term is to be more confident when communicating with others.<br /><br />
                <strong>Action Plan:</strong> To achieve this goal I will be more mindful of how I speak and interact with my colleagues and our customers.<br /><br />
                <strong>Measure of Success:</strong> To measure the success of this goal, I can discuss my progress with my Team Lead in our 1-on-1 meetings and seek feedback.<br /><br />
                <strong>Reflection:</strong> Overall I think I made good progress towards this goal throughout the course of my second four month co-op term here at P&P Optica. Working in a production level programming environment for the first time was definitely intimidating. However as I began developing the new data post-processing tool for the team, I started to feel more confident - not only about the solutions and the tool I was writing - but also when communicating about my script to my coworkers. Coming out of this co-op, I feel more confident when it comes to writing Python tools for data analysis, post-processing, and communicating these work items. My supervisor Jenny was always very helpful and consistently pushed me to speak my mind regarding code solutions which I appreciated as it helped me feel more confident as well.
                <br /><br />
                My evaluation did point out that I still hesitate a bit when it comes to decision making, which I think is fair. I have a tendency to second-guess myself before speaking up, especially in a co-op role where it can feel like I haven't earned the experience to make the call. It's something I want to keep working on going forward, and Jenny's advice stuck with me: an idea is only useful once you actually say it out loud.
              </p>
            </div>
            <div className="bg-base-200 p-6 rounded-xl shadow-inner">
              <h3 className="font-bold text-xl mb-3 text-secondary">Goal 3: Professional & Ethical Behaviour</h3>
              <p className="text-lg leading-relaxed">
                <strong>Goal:</strong> My third goal for this work term is to improve my ability to manage my time effectively while working on multiple projects.<br /><br />
                <strong>Action Plan:</strong> To achieve this goal, I plan to ensure that I dedicate sufficient time to each project I am assigned and avoid becoming overly focused on a single task.<br /><br />
                <strong>Measure of Success:</strong> To measure the success of this goal, I will track my ability to complete projects by their deadlines and seek feedback from my Team Lead regarding my time management and prioritization skills.<br /><br />
                <strong>Reflection:</strong> During my second term at P&P Optica, I was told it was the busiest year they ever had, and this was definitely true. There were a great number of projects running simultaneously, and the Data Services Team works on ALL customer facing projects. As such, I got the chance to balance multiple tasks at once and I was successfully able to balance them all. Between the different types of work we do, we wear so many hats, so I can't say it wasn't a challenge sometimes. Overall, my supervisor was very happy with my performance during this extremely busy timeline, and I feel more confident with my time management skills as a result.
              </p>
            </div>
          </div>
        </div>
        {/* Conclusion Section */}
        <div className='bg-base-300 p-8 rounded-xl flex flex-col md:flex-row-reverse gap-8 items-center'>
          <div className="md:w-1/2">
            <h2 className="font-bold text-2xl mb-4">Conclusion & Acknowledgements</h2>
            <p className="text-lg leading-relaxed">
              This work term at P&P Optica was another incredible experience for me. Returning for a second term allowed me to build on what I had learned previously while taking on new responsibilities and becoming more comfortable working in a professional environment. My supervisor rated my overall performance as Very Good for the term, with Outstanding marks for quality of work and progress toward my learning goals. Overall, I'm extremely proud of the work I've done and the skills I developed at PPO.
              <br /><br />
              I am especially grateful to Jenny Udema for her continued guidance and encouragement throughout the term. Her feedback helped me become more confident in my technical abilities and encouraged me to speak up and trust my ideas, something I know I still have room to grow into. She's reminded me more than once that an idea worth having is only worth something once you actually voice it, and that's advice I plan to carry into my future career.
              <br /><br />
              One of the things I will remember most about this work term is the community of coworkers I had the opportunity to work with. The co-ops and full-time employees made the workplace a great environment to be part of, which made saying goodbye at the end of the term difficult. The farewell cake we received near the end of the term was a nice way to celebrate the time we spent together.
              <br /><br />
              As I move forward, I am grateful for everything I learned during my time at P&P Optica. From developing Python tools and testing the Smart Imaging System, to collecting customer data and improving my communication skills; this experience has helped prepare me for my future career in software engineering and I am very excited to see what the future has in store.
            </p>
          </div>
          <div className='w-full md:w-1/2 flex justify-center flex-shrink-0'>
            <img
              src={farewellCake}
              alt="Farewell cake for the Data Services co-ops"
              className='w-full max-w-[550px] aspect-square rounded-[20%] shadow-lg object-cover'
            />
          </div>
        </div>
      </section>
    </div>
  );
}

export default WT4Report;